### ISSUE TITLE
default reset css

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/microlinkjs#59]
Because the microlink card is inline, global css can modify the default card style.

For avoid that, a good approach could be ship reset styles with the card CSS, like:

```css
.microlink_card__content_title,
.microlink_card__content_description {
    margin: 0;
}
```
